/* ISC license. */

/* Generated by: ./configure --prefix=/home/jeremy/opt --with-lib=/home/jeremy/opt/lib/skalibs --with-lib=/home/jeremy/opt/lib/execline --with-include=/home/jeremy/opt/include */

#ifndef S6_CONFIG_H
#define S6_CONFIG_H

#define S6_VERSION "2.5.0.0"
#define S6_BINPREFIX ""
#define S6_EXTBINPREFIX ""
#define S6_LIBEXECPREFIX "/home/jeremy/opt/libexec/"

#endif
